FROM python:3.9-buster

WORKDIR /app

COPY graphql .
COPY poetry.lock .
COPY pyproject.toml .

RUN python3 -m pip install poetry
RUN python3 -m pip install pycryptodome
RUN poetry config virtualenvs.create false
RUN poetry install

ENTRYPOINT [ "indexer", "graphql", "--mongo", "mongodb://test:test@mongo:27017", "--port", "8080" ]
