version: '3.6'

services:
  mongo:
    image: mongo:6.0.8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    volumes:
      - etcd_data:/bitnami/etcd


  adventurers_indexer:
    image: quay.io/apibara/sink-mongo:0.3
    depends_on:
      - etcd
    restart: always
    command:
      - run
      - --allow-env=/data/env-mainnet
      - /data/src/adventurers.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: adventurers
      AUTH_TOKEN: dna_jX3t04zs9zywBnHWVmUq

  battles_indexer:
    image: quay.io/apibara/sink-mongo:0.3
    depends_on:
      - etcd
    restart: always
    command:
      - run
      - --allow-env=/data/env-mainnet
      - /data/src/battles.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: battles
      AUTH_TOKEN: dna_jX3t04zs9zywBnHWVmUq

  beasts_indexer:
    image: quay.io/apibara/sink-mongo:0.3
    depends_on:
      - etcd
    restart: always
    command:
      - run
      - --allow-env=/data/env-mainnet
      - /data/src/beasts.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: beasts
      AUTH_TOKEN: dna_jX3t04zs9zywBnHWVmUq

  discoveries_indexer:
    image: quay.io/apibara/sink-mongo:0.3
    depends_on:
      - etcd
    restart: always
    command:
      - run
      - --allow-env=/data/env-mainnet
      - /data/src/discoveries.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: discoveries
      AUTH_TOKEN: dna_jX3t04zs9zywBnHWVmUq

  items_indexer:
    image: quay.io/apibara/sink-mongo:0.3
    depends_on:
      - etcd
    restart: always
    command:
      - run
      - --allow-env=/data/env-mainnet
      - /data/src/items.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: items
      AUTH_TOKEN: dna_jX3t04zs9zywBnHWVmUq

  scores_indexer:
    image: quay.io/apibara/sink-mongo:0.3
    depends_on:
      - etcd
    restart: always
    command:
      - run
      - --allow-env=/data/env-mainnet
      - /data/src/scores.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: scores
      AUTH_TOKEN: dna_jX3t04zs9zywBnHWVmUq

  entropy_indexer:
    image: quay.io/apibara/sink-mongo:0.3
    depends_on:
      - etcd
      - mongo
    restart: always
    command:
      - run
      - --allow-env=/data/env-goerli
      - /data/src/entropy.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: entropy
      AUTH_TOKEN: dna_jX3t04zs9zywBnHWVmUq

volumes:
  etcd_data:
  mongo_data: