version: '3.6'

services:
  mongo:
    image: mongo:6.0.8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./scripts/mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - indexer

  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    volumes:
      - etcd_data:/bitnami/etcd
    networks:
      - indexer


  adventurers_indexer:
    image: quay.io/apibara/sink-mongo:0.4.2
    depends_on:
      - etcd
      - mongo
    restart: always
    command:
      - run
      - --allow-env=/data/env-sepolia
      - /data/src/adventurers.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: adventurers
      AUTH_TOKEN: ${AUTH_TOKEN}
    networks:
      - indexer

  battles_indexer:
    image: quay.io/apibara/sink-mongo:0.4.2
    depends_on:
      - etcd
      - mongo
    restart: always
    command:
      - run
      - --allow-env=/data/env-sepolia
      - /data/src/battles.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: battles
      AUTH_TOKEN: ${AUTH_TOKEN}
    networks:
      - indexer

  beasts_indexer:
    image: quay.io/apibara/sink-mongo:0.4.2
    depends_on:
      - etcd
      - mongo
    restart: always
    command:
      - run
      - --allow-env=/data/env-sepolia
      - /data/src/beasts.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: beasts
      AUTH_TOKEN: ${AUTH_TOKEN}
    networks:
      - indexer

  discoveries_indexer:
    image: quay.io/apibara/sink-mongo:0.4.2
    depends_on:
      - etcd
      - mongo
    restart: always
    command:
      - run
      - --allow-env=/data/env-sepolia
      - /data/src/discoveries.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: discoveries
      AUTH_TOKEN: ${AUTH_TOKEN}
    networks:
      - indexer

  items_indexer:
    image: quay.io/apibara/sink-mongo:0.4.2
    depends_on:
      - etcd
      - mongo
    restart: always
    command:
      - run
      - --allow-env=/data/env-sepolia
      - /data/src/items.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: items
      AUTH_TOKEN: ${AUTH_TOKEN}
    networks:
      - indexer

  scores_indexer:
    image: quay.io/apibara/sink-mongo:0.4.2
    depends_on:
      - etcd
      - mongo
    restart: always
    command:
      - run
      - --allow-env=/data/env-sepolia
      - /data/src/scores.ts
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: scores
      AUTH_TOKEN: ${AUTH_TOKEN}
    networks:
      - indexer
  
volumes:
  etcd_data:
  mongo_data:

networks:
  indexer: