"use client";

import "./globals.css";
import { VT323 } from "next/font/google";
import { InjectedConnector, StarknetConfig } from "@starknet-react/core";
import CartridgeConnector from "@cartridge/connector";
import { useMemo } from "react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const vt323 = VT323({
  subsets: ["latin-ext"],
  weight: ["400"],
  variable: "--font-vt323",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const connectors = useMemo(
    () => [
      new InjectedConnector({ options: { id: "argentX" } }),
      // new InjectedConnector({ options: { id: "braavos" } }),
      // new InjectedConnector({ options: { id: "guildly" } }),
      // new CartridgeConnector([
      //   {
      //     target: ModuleAddr.Labor,
      //     method: 'harvest',
      //   },
      // ]),
    ],
    []
  );
  return (
    <html lang="en">
      <body
        className={`${vt323.variable} font-mono bg-terminal-black text-terminal-green`}
      >
        <StarknetConfig connectors={connectors} autoConnect>
          {children}
        </StarknetConfig>
      </body>
    </html>
  );
}
