"use client";

import "./globals.css";
import { Connect } from "./providers/Connect";
import { VT323 } from "next/font/google";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const vt323 = VT323({
  subsets: ["latin-ext"],
  weight: ["400"],
  variable: "--font-vt323",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${vt323.variable} font-mono bg-terminal-black text-terminal-green`}
      >
        <Connect>{children}</Connect>
      </body>
    </html>
  );
}
