"use client";
import "./globals.css";
import { InjectedConnector, StarknetConfig } from "@starknet-react/core";
import CartridgeConnector from "@cartridge/connector";
import { useMemo } from "react";
import { AdventurerProvider } from "./context/AdventurerProvider";
import { ApolloClient, InMemoryCache, ApolloProvider } from "@apollo/client";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const connectors = useMemo(
    () => [
      new InjectedConnector({ options: { id: "argentX" } }),
      new InjectedConnector({ options: { id: "braavos" } }),
      // new InjectedConnector({ options: { id: "guildly" } }),
      // new CartridgeConnector([
      //   {
      //     target: ModuleAddr.Labor,
      //     method: 'harvest',
      //   },
      // ]),
    ],
    []
  );

  const client = new ApolloClient({
    uri: "http://3.215.42.99:8080/graphql",
    cache: new InMemoryCache(),
  });

  return (
    <html lang="en">
      <body className="bg-black text-terminal-green">
        <ApolloProvider client={client}>
          <StarknetConfig connectors={connectors} autoConnect>
            <AdventurerProvider>{children}</AdventurerProvider>
          </StarknetConfig>
        </ApolloProvider>
      </body>
    </html>
  );
}
