export type Dict<T> = { [key: number]: T };
export type DictString<T> = { [key: string]: T };

export class GameData {
  CONTRACTS: DictString<string>;
  BEASTS: Dict<string>;
  BEAST_TIERS: Dict<number>;
  BEAST_TYPES: Dict<string>;
  BEAST_ATTACK_TYPES: Dict<string>;
  BEAST_ARMOR_TYPES: Dict<string>;
  ITEMS: Dict<string>;
  RACES: Dict<string>;
  ORDERS: Dict<string>;
  STATS: Dict<string>;
  OBSTACLES: Dict<string>;
  DISCOVERY_TYPES: Dict<string>;
  ITEM_DISCOVERY_TYPES: Dict<string>;
  ITEM_TYPES: Dict<string>;
  MATERIALS: Dict<string>;
  ITEM_NAME_PREFIXES: Dict<string>;
  ITEM_NAME_SUFFIXES: Dict<string>;
  ITEM_SUFFIXES: Dict<string>;
  STATUS: Dict<string>;
  SLOTS: Dict<string>;
  BEAST_IMAGES: DictString<string>;
  BEAST_ATTACK_LOCATION: DictString<string>;
  ADVENTURER_ANIMATIONS: DictString<string>;
  ADVENTURER_SOUNDS: DictString<string>;

  constructor() {
    this.CONTRACTS = {
      goerliAdventurer:
        "0x035d755a23ec72df90819f584d9a1849bbc21fa77f96d25e03f1736883895248",
      goerliBeast:
        "0x000f4dbfe5d15792aa91025e42ee1d74c22bdeb1eef0b9bc19a37216377290c1",
      goerliLoot:
        "0x065669e15c8f1a7f17b7062e4eb1b709b922b931b93c59577f1848a85c30ab1f",
      devnetAdventurer:
        "0x005160ffc8910638190fbe80296932ce90be9091f622b30b299ed81c7be7d359",
      devnetBeast:
        "0x061533cb6f21d230aeef9ac2aecf0c70679d1d50d9d61f11bd6a6113cf3d7d85",
      devnetLoot:
        "0x040583a9197a52f289a5f6f03981ace0b3dfcc7496137fa292ec67796be22766",
    };

    this.BEASTS = {
      1: "Warlock",
      2: "Rakshasa",
      3: "Jiangshi",
      4: "Kitsune",
      5: "Basilisk",
      6: "Gorgon",
      7: "Anansi",
      8: "Lich",
      9: "Chimera",
      10: "Wendigo",
      11: "Cerberus",
      12: "Werewolf",
      13: "Banshee",
      14: "Draugr",
      15: "Vampire",
      16: "Goblin",
      17: "Ghoul",
      18: "Pixie",
      19: "Sprite",
      20: "Kappa",
      21: "Fairy",
      22: "Leprechaun",
      23: "Kelpie",
      24: "Wraith",
      25: "Gnome",
      26: "Griffin",
      27: "Manticore",
      28: "Phoenix",
      29: "Dragon",
      30: "Minotaur",
      31: "Harpy",
      32: "Arachne",
      33: "Nue",
      34: "Skinwalker",
      35: "Chupacabra",
      36: "Weretiger",
      37: "Wyvern",
      38: "Roc",
      39: "Qilin",
      40: "Pegasus",
      41: "Hippogriff",
      42: "Fenrir",
      43: "Jaguar",
      44: "Ammit",
      45: "DireWolf",
      46: "Bear",
      47: "Wolf",
      48: "Scorpion",
      49: "Spider",
      50: "Rat",
      51: "Cyclops",
      52: "Golem",
      53: "Titan",
      54: "Yeti",
      55: "Troll",
      56: "Oni",
      57: "Ogre",
      58: "Juggernaut",
      59: "Bigfoot",
      60: "Orc",
      61: "Behemoth",
      62: "Ent",
      63: "Giant",
      64: "Kraken",
      65: "Leviathan",
      66: "Skeleton",
      67: "Nephilim",
      68: "Tarrasque",
      69: "Beserker",
      70: "Balrog",
      71: "Ettin",
      72: "Jotunn",
      73: "Hydra",
      74: "NemeanLion",
      75: "Colossus",
    };

    this.BEAST_TIERS = {
      // Magical T1s
      1: 1,
      2: 1,
      3: 1,
      4: 1,
      5: 1,
      // Magical T2s
      6: 2,
      7: 2,
      8: 2,
      9: 2,
      10: 2,
      // Magical T3s
      11: 3,
      12: 3,
      13: 3,
      14: 3,
      15: 3,
      // Magical T4s
      16: 4,
      17: 4,
      18: 4,
      19: 4,
      20: 4,
      // Magical T5s
      21: 5,
      22: 5,
      23: 5,
      24: 5,
      25: 5,
      // Hunter T1s
      26: 1,
      27: 1,
      28: 1,
      29: 1,
      30: 1,
      // Hunter T2s
      31: 2,
      32: 2,
      33: 2,
      34: 2,
      35: 2,
      // Hunter T3s
      36: 3,
      37: 3,
      38: 3,
      39: 3,
      40: 3,
      // Hunter T4s
      41: 4,
      42: 4,
      43: 4,
      44: 4,
      45: 4,
      // Hunter T5s
      46: 5,
      47: 5,
      48: 5,
      49: 5,
      50: 5,
      // Brute T1s
      51: 1,
      52: 1,
      53: 1,
      54: 1,
      55: 1,
      // Brute T2s
      56: 2,
      57: 2,
      58: 2,
      59: 2,
      60: 2,
      // Brute T3s
      61: 3,
      62: 3,
      63: 3,
      64: 3,
      65: 3,
      // Brute T4s
      66: 4,
      67: 4,
      68: 4,
      69: 4,
      70: 4,
      // Brute T5s
      71: 5,
      72: 5,
      73: 5,
      74: 5,
      75: 5,
    };

    this.BEAST_TYPES = {
      // Magical Beasts
      1: "Magical",
      2: "Magical",
      3: "Magical",
      4: "Magical",
      5: "Magical",
      6: "Magical",
      7: "Magical",
      8: "Magical",
      9: "Magical",
      10: "Magical",
      11: "Magical",
      12: "Magical",
      13: "Magical",
      14: "Magical",
      15: "Magical",
      16: "Magical",
      17: "Magical",
      18: "Magical",
      19: "Magical",
      20: "Magical",
      21: "Magical",
      22: "Magical",
      23: "Magical",
      24: "Magical",
      25: "Magical",
      // Hunter Beasts
      26: "Hunter",
      27: "Hunter",
      28: "Hunter",
      29: "Hunter",
      30: "Hunter",
      31: "Hunter",
      32: "Hunter",
      33: "Hunter",
      34: "Hunter",
      35: "Hunter",
      36: "Hunter",
      37: "Hunter",
      38: "Hunter",
      39: "Hunter",
      40: "Hunter",
      41: "Hunter",
      42: "Hunter",
      43: "Hunter",
      44: "Hunter",
      45: "Hunter",
      46: "Hunter",
      47: "Hunter",
      48: "Hunter",
      49: "Hunter",
      50: "Hunter",
      // Brute Beasts
      51: "Brute",
      52: "Brute",
      53: "Brute",
      54: "Brute",
      55: "Brute",
      56: "Brute",
      57: "Brute",
      58: "Brute",
      59: "Brute",
      60: "Brute",
      61: "Brute",
      62: "Brute",
      63: "Brute",
      64: "Brute",
      65: "Brute",
      66: "Brute",
      67: "Brute",
      68: "Brute",
      69: "Brute",
      70: "Brute",
      71: "Brute",
      72: "Brute",
      73: "Brute",
      74: "Brute",
      75: "Brute",
    };

    this.BEAST_ATTACK_TYPES = { 1: "Magic", 2: "Blade", 3: "Bludgeon" };

    this.BEAST_ARMOR_TYPES = { 1: "Cloth", 2: "Hide", 3: "Metal" };

    this.ITEMS = {
      1: "Pendant",
      2: "Necklace",
      3: "Amulet",
      4: "Silver Ring",
      5: "Bronze Ring",
      6: "Platinum Ring",
      7: "Titanium Ring",
      8: "Gold Ring",
      9: "Ghost Wand",
      10: "Grave Wand",
      11: "Bone Wand",
      12: "Wand",
      13: "Grimoire",
      14: "Chronicle",
      15: "Tome",
      16: "Book",
      17: "Divine Robe",
      18: "Silk Robe",
      19: "Linen Robe",
      20: "Robe",
      21: "Shirt",
      22: "Crown",
      23: "Divine Hood",
      24: "Silk Hood",
      25: "Linen Hood",
      26: "Hood",
      27: "Brightsilk Sash",
      28: "Silk Sash",
      29: "Wool Sash",
      30: "Linen Sash",
      31: "Sash",
      32: "Divine Slippers",
      33: "Silk Slippers",
      34: "Wool Shoes",
      35: "Linen Shoes",
      36: "Shoes",
      37: "Divine Gloves",
      38: "Silk Gloves",
      39: "Wool Gloves",
      40: "Linen Gloves",
      41: "Gloves",
      42: "Katana",
      43: "Falchion",
      44: "Scimitar",
      45: "Long Sword",
      46: "Short Sword",
      47: "Demon Husk",
      48: "Dragonskin Armor",
      49: "Studded Leather Armor",
      50: "Hard Leather Armor",
      51: "Leather Armor",
      52: "Demon Crown",
      53: "Dragons Crown",
      54: "War Cap",
      55: "Leather Cap",
      56: "Cap",
      57: "Demonhide Belt",
      58: "Dragonskin Belt",
      59: "Studded Leather Belt",
      60: "Hard Leather Belt",
      61: "Leather Belt",
      62: "Demonhide Boots",
      63: "Dragonskin Boots",
      64: "Studded Leather Boots",
      65: "Hard Leather Boots",
      66: "Leather Boots",
      67: "Demons Hands",
      68: "Dragonskin Gloves",
      69: "Studded Leather Gloves",
      70: "Hard Leather Gloves",
      71: "Leather Gloves",
      72: "Warhammer",
      73: "Quarterstaff",
      74: "Maul",
      75: "Mace",
      76: "Club",
      77: "Holy Chestplate",
      78: "Ornate Chestplate",
      79: "Plate Mail",
      80: "Chain Mail",
      81: "Ring Mail",
      82: "Ancient Helm",
      83: "Ornate Helm",
      84: "Great Helm",
      85: "Full Helm",
      86: "Helm",
      87: "Ornate Belt",
      88: "War Belt",
      89: "Plated Belt",
      90: "Mesh Belt",
      91: "Heavy Belt",
      92: "Holy Greaves",
      93: "Ornate Greaves",
      94: "Greaves",
      95: "Chain Boots",
      96: "Heavy Boots",
      97: "Holy Gauntlets",
      98: "Ornate Gauntlets",
      99: "Gauntlets",
      100: "Chain Gloves",
      101: "Heavy Gloves",
    };

    this.ITEM_TYPES = {
      1: "Necklace",
      2: "Necklace",
      3: "Necklace",
      4: "Ring",
      5: "Ring",
      6: "Ring",
      7: "Ring",
      8: "Ring",
      9: "Magic",
      10: "Magic",
      11: "Magic",
      12: "Magic",
      13: "Magic",
      14: "Magic",
      15: "Magic",
      16: "Magic",
      17: "Cloth",
      18: "Cloth",
      19: "Cloth",
      20: "Cloth",
      21: "Cloth",
      22: "Cloth",
      23: "Cloth",
      24: "Cloth",
      25: "Cloth",
      26: "Cloth",
      27: "Cloth",
      28: "Cloth",
      29: "Cloth",
      30: "Cloth",
      31: "Cloth",
      32: "Cloth",
      33: "Cloth",
      34: "Cloth",
      35: "Cloth",
      36: "Cloth",
      37: "Cloth",
      38: "Cloth",
      39: "Cloth",
      40: "Cloth",
      41: "Cloth",
      42: "Blade",
      43: "Blade",
      44: "Blade",
      45: "Blade",
      46: "Blade",
      47: "Hide",
      48: "Hide",
      49: "Hide",
      50: "Hide",
      51: "Hide",
      52: "Hide",
      53: "Hide",
      54: "Hide",
      55: "Hide",
      56: "Hide",
      57: "Hide",
      58: "Hide",
      59: "Hide",
      60: "Hide",
      61: "Hide",
      62: "Hide",
      63: "Hide",
      64: "Hide",
      65: "Hide",
      66: "Hide",
      67: "Hide",
      68: "Hide",
      69: "Hide",
      70: "Hide",
      71: "Hide",
      72: "Bludgeon",
      73: "Bludgeon",
      74: "Bludgeon",
      75: "Bludgeon",
      76: "Bludgeon",
      78: "Metal",
      79: "Metal",
      80: "Metal",
      81: "Metal",
      82: "Metal",
      83: "Metal",
      84: "Metal",
      85: "Metal",
      86: "Metal",
      87: "Metal",
      88: "Metal",
      89: "Metal",
      90: "Metal",
      91: "Metal",
      92: "Metal",
      93: "Metal",
      94: "Metal",
      95: "Metal",
      96: "Metal",
      97: "Metal",
      98: "Metal",
      99: "Metal",
      100: "Metal",
      101: "Metal",
    };

    this.RACES = {
      1: "Elf",
      2: "Fox",
      3: "Giant",
      4: "Human",
      5: "Orc",
      6: "Demon",
      7: "Goblin",
      8: "Fish",
      9: "Cat",
      10: "Frog",
    };

    this.ORDERS = {
      1: "Power",
      2: "Giants",
      3: "Titans",
      4: "Skill",
      5: "Perfection",
      6: "Brilliance",
      7: "Enlightenment",
      8: "Protection",
      9: "Twins",
      10: "Reflection",
      11: "Detection",
      12: "Fox",
      13: "Vitriol",
      14: "Fury",
      15: "Rage",
      16: "Anger",
    };

    this.STATS = {
      2: "Strength",
      3: "Dexterity",
      4: "Vitality",
      5: "Intelligence",
      6: "Wisdom",
      7: "Charisma",
      8: "Luck",
    };

    this.OBSTACLES = {
      1: "Demonic Alter",
      2: "Curse",
      3: "Hex",
      4: "Magic Lock",
      5: "Dark Mist",
      6: "Collapsing Ceiling",
      7: "Crushing Walls",
      8: "Rockslide",
      9: "Tumbling Boulders",
      10: "Swinging Logs",
      11: "Pendulum Blades",
      12: "Flame Jet",
      13: "Poision Dart",
      14: "Spiked Pit",
      15: "Hidden Arrow",
    };

    this.DISCOVERY_TYPES = {
      0: "Nothing",
      1: "Beast",
      2: "Obstacle",
      3: "Item",
      4: "Adventurer",
    };

    this.ITEM_DISCOVERY_TYPES = {
      0: "Gold",
      1: "Loot",
      2: "Health",
    };

    this.MATERIALS = {
      0: "Generic",
      1000: "Generic Metal",
      1001: "Ancient Metal",
      1002: "Holy Metal",
      1003: "Ornate Metal",
      1004: "Gold Metal",
      1005: "Silver Metal",
      1006: "Bronze Metal",
      1007: "Platinum Metal",
      1008: "Titanium Metal",
      1009: "Steel Metal",
      2000: "Generic Cloth",
      2001: "Royal Cloth",
      2002: "Divine Cloth",
      2003: "Brightsilk Cloth",
      2004: "Silk Cloth",
      2005: "Wool Cloth",
      2006: "Linen Cloth",
      3000: "Generic Biotic",
      3100: "Demon Generic Biotic",
      3101: "Demon Blood Biotic",
      3102: "Demon Bones Biotic",
      3103: "Demon Brain Biotic",
      3104: "Demon Eyes Biotic",
      3105: "Demon Hide Biotic",
      3106: "Demon Flesh Biotic",
      3107: "Demon Hair Biotic",
      3108: "Demon Heart Biotic",
      3109: "Demon Entrails Biotic",
      3110: "Demon Hands Biotic",
      3111: "Demon Feet Biotic",
      3200: "Dragon Generic Biotic",
      3201: "Dragon Blood Biotic",
      3202: "Dragon Bones Biotic",
      3203: "Dragon Brain Biotic",
      3204: "Dragon Eyes Biotic",
      3205: "Dragon Skin Biotic",
      3206: "Dragon Flesh Biotic",
      3207: "Dragon Hair Biotic",
      3208: "Dragon Heart Biotic",
      3209: "Dragon Entrails Biotic",
      3210: "Dragon Hands Biotic",
      3211: "Dragon Feet Biotic",
      3300: "Animal Generic Biotic",
      3301: "Animal Blood Biotic",
      3302: "Animal Bones Biotic",
      3303: "Animal Brain Biotic",
      3304: "Animal Eyes Biotic",
      3305: "Animal Hide Biotic",
      3306: "Animal Flesh Biotic",
      3307: "Animal Hair Biotic",
      3308: "Animal Heart Biotic",
      3309: "Animal Entrails Biotic",
      3310: "Animal Hands Biotic",
      3311: "Animal Feet Biotic",
      3400: "Human Generic Biotic",
      3401: "Human Blood Biotic",
      3402: "Human Bones Biotic",
      3403: "Human Brain Biotic",
      3404: "Human Eyes Biotic",
      3405: "Human Hide Biotic",
      3406: "Human Flesh Biotic",
      3407: "Human Hair Biotic",
      3408: "Human Heart Biotic",
      3409: "Human Entrails Biotic",
      3410: "Human Hands Biotic",
      3411: "Human Feet Biotic",
      4000: "Generic Paper",
      4001: "Magical Paper",
      5000: "Generic Wood",
      5100: "Generic Hardwood",
      5101: "Walnut Hardwood",
      5102: "Mahogany Hardwood",
      5103: "Maple Hardwood",
      5104: "Oak Hardwood",
      5105: "Rosewood Hardwood",
      5106: "Cherry Hardwood",
      5107: "Balsa Hardwood",
      5108: "Birch Hardwood",
      5109: "Holly Hardwood",
      5200: "Generic Softwood",
      5201: "Cedar Softwood",
      5202: "Pine Softwood",
      5203: "Fir Softwood",
      5204: "Hemlock Softwood",
      5205: "Spruce Softwood",
      5206: "Elder Softwood",
      5207: "Yew Softwood",
    };

    this.ITEM_NAME_PREFIXES = {
      1: "Agony ",
      2: "Apocalypse ",
      3: "Armageddon ",
      4: "Beast ",
      5: "Behemoth ",
      6: "Blight ",
      7: "Blood ",
      8: "Bramble ",
      9: "Brimstone ",
      10: "Brood ",
      11: "Carrion ",
      12: "Cataclysm ",
      13: "Chimeric ",
      14: "Corpse ",
      15: "Corruption ",
      16: "Damnation ",
      17: "Death ",
      18: "Demon ",
      19: "Dire ",
      20: "Dragon ",
      21: "Dread ",
      22: "Doom ",
      23: "Dusk ",
      24: "Eagle ",
      25: "Empyrean ",
      26: "Fate ",
      27: "Foe ",
      28: "Gale ",
      29: "Ghoul ",
      30: "Gloom ",
      31: "Glyph ",
      32: "Golem ",
      33: "Grim ",
      34: "Hate ",
      35: "Havoc ",
      36: "Honour ",
      37: "Horror ",
      38: "Hypnotic ",
      39: "Kraken ",
      40: "Loath ",
      41: "Maelstrom ",
      42: "Mind ",
      43: "Miracle ",
      44: "Morbid ",
      45: "Oblivion ",
      46: "Onslaught ",
      47: "Pain ",
      48: "Pandemonium ",
      49: "Phoenix ",
      50: "Plague ",
      51: "Rage ",
      52: "Rapture ",
      53: "Rune ",
      54: "Skull ",
      55: "Sol ",
      56: "Soul ",
      57: "Sorrow ",
      58: "Spirit ",
      59: "Storm ",
      60: "Tempest ",
      61: "Torment ",
      62: "Vengeance ",
      63: "Victory ",
      64: "Viper ",
      65: "Vortex ",
      66: "Woe ",
      67: "Wrath ",
      68: "Lights ",
      69: "Shimmering ",
    };

    this.ITEM_NAME_SUFFIXES = {
      1: "Bane ",
      2: "Root ",
      3: "Bite ",
      4: "Song ",
      5: "Roar ",
      6: "Grasp ",
      7: "Instrument ",
      8: "Glow ",
      9: "Bender ",
      10: "Shadow ",
      11: "Whisper ",
      12: "Shout ",
      13: "Growl ",
      14: "Tear ",
      15: "Peak ",
      16: "Form ",
      17: "Sun ",
      18: "Moon ",
    };

    this.ITEM_SUFFIXES = {
      1: "Of Power",
      2: "Of Giant",
      3: "Of Titans",
      4: "Of Skill",
      5: "Of Perfection",
      6: "Of Brilliance",
      7: "Of Enlightenment",
      8: "Of Protection",
      9: "Of Anger",
      10: "Of Rage",
      11: "Of Fury",
      12: "Of Vitriol",
      13: "Of The Fox",
      14: "Of Detection",
      15: "Of Reflection",
      16: "Of The Twins",
    };

    this.STATUS = { 0: "Closed", 1: "Open" };

    this.SLOTS = {
      1: "Weapon",
      2: "Chest",
      3: "Head",
      4: "Waist",
      5: "Foot",
      6: "Hand",
      7: "Neck",
      8: "Ring",
    };

    this.BEAST_IMAGES = {
      Phoenix: "/monsters/phoenix.png",
      Griffin: "/monsters/griffin.png",
      Minotaur: "/monsters/minotaur.png",
      Basilisk: "/monsters/basilisk.png",
      Gnome: "/monsters/gnome.png",
      Wraith: "/monsters/wraith.png",
      Ghoul: "/monsters/ghoul.png",
      Goblin: "/monsters/goblin.png",
      Skeleton: "/monsters/skeleton.png",
      Golem: "/monsters/golem.png",
      Giant: "/monsters/giant.png",
      Yeti: "/monsters/yeti.png",
      Orc: "/monsters/orc.png",
      Berserker: "/monsters/berserker.png",
      Ogre: "/monsters/ogre.png",
      Dragon: "/monsters/dragon.png",
      Vampire: "/monsters/vampire.png",
      Werewolf: "/monsters/werewolf.png",
      Spider: "/monsters/spider.png",
      Rat: "/monsters/rat.png",
    };

    this.BEAST_ATTACK_LOCATION = {
      Phoenix: "/icons/loot/head.svg",
      Griffin: "/icons/loot/chest.svg",
      Minotaur: "/icons/loot/hand.svg",
      Basilisk: "/icons/loot/waist.svg",
      Gnome: "/icons/loot/foot.svg",
      Wraith: "/icons/loot/chest.svg",
      Ghoul: "/icons/loot/hand.svg",
      Goblin: "/icons/loot/waist.svg",
      Skeleton: "/icons/loot/foot.svg",
      Golem: "/icons/loot/head.svg",
      Giant: "/icons/loot/hand.svg",
      Yeti: "/icons/loot/waist.svg",
      Orc: "/icons/loot/foot.svg",
      Berserker: "/icons/loot/head.svg",
      Ogre: "/icons/loot/chest.svg",
      Dragon: "/icons/loot/waist.svg",
      Vampire: "/icons/loot/foot.svg",
      Werewolf: "/icons/loot/head.svg",
      Spider: "/icons/loot/chest.svg",
      Rat: "/icons/loot/hand.svg",
    };

    this.ADVENTURER_ANIMATIONS = {
      Create: "idle",
      Flee: "run",
      Ambush: "damage",
      Attack1: "attack1",
      Attack2: "attack2",
      Attack3: "attack3",
      Dead: "die",
      Upgrade: "drawSword",
      DiscoverItem: "discoverItem",
      DiscoverBeast: "drawSword",
      AvoidObstacle1: "jump",
      AvoidObstacle2: "slide",
      HitByObstacle: "damage",
      Multicall: "discoverItem",
      HitByBeast: "damage",
    };

    this.ADVENTURER_SOUNDS = {
      Create: "fight_ui_sound.mp3",
      Flee: "fight_ui_sound.mp3",
      Ambush: "fight_ui_sound.mp3",
      Attack: "fight_ui_sound.mp3",
      Slayed: "fight_ui_sound.mp3",
      Dead: "fight_ui_sound.mp3",
      Upgrade: "fight_ui_sound.mp3",
      DiscoverItem: "fight_ui_sound.mp3",
      DiscoverBeast: "fight_ui_sound.mp3",
      AvoidObstacle: "fight_ui_sound.mp3",
      HitByObstacle: "fight_ui_sound.mp3",
      Multicall: "fight_ui_sound.mp3",
    };
  }
}
