"use client";
import "./globals.css";
import {
  InjectedConnector,
  StarknetConfig,
  useAccount,
} from "@starknet-react/core";
import { useMemo } from "react";
import { AdventurerProvider } from "./context/AdventurerProvider";
import { TransactionCartProvider } from "./context/TransactionCartProvider";
import { UIProvider } from "./context/UIProvider";
import { ApolloClient, InMemoryCache, ApolloProvider } from "@apollo/client";
import { IndexerProvider } from "./context/IndexerProvider";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { account } = useAccount();

  const connectors = useMemo(
    () => [
      new InjectedConnector({ options: { id: "argentX" } }),
      new InjectedConnector({ options: { id: "braavos" } }),
      // new InjectedConnector({ options: { id: "guildly" } }),
      // new CartridgeConnector([
      //   {
      //     target: ModuleAddr.Labor,
      //     method: 'harvest',
      //   },
      // ]),
    ],
    []
  );

  return (
    <html lang="en">
      <body className="bg-black text-terminal-green">
        <IndexerProvider>
          <StarknetConfig connectors={connectors} autoConnect>
            <UIProvider>
              <TransactionCartProvider>
                <AdventurerProvider>{children}</AdventurerProvider>
              </TransactionCartProvider>
            </UIProvider>
          </StarknetConfig>
        </IndexerProvider>
      </body>
    </html>
  );
}
